{% set name = "lightning-cloud" %}
{% set version = "0.5.68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning_cloud-{{ version }}.tar.gz
  sha256: b0c30d18624a76e88588197a45638d2eeebdba1b017644f1f7bd49eb8f877dc6

build:
  entry_points:
    - lightning_cloud=lightning_cloud.cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - boto3
    - click
    - fastapi
    - protobuf
    - pyjwt
    - python >=3.7
    - python-multipart
    - requests
    - rich
    - six
    - urllib3
    - uvicorn
    - websocket-client

test:
  imports:
    - lightning_cloud
  commands:
    - pip check
    - lightning_cloud --help
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Lightning Cloud
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
